name: MFashionStore CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.x"
  SOLUTION_PATH: "MFashionStore.sln"
  API_PROJECT_PATH: "MFashionStoreAPI"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Generate appsettings.json from secret
        run: |
          mkdir -p ${{ env.API_PROJECT_PATH }}
          echo '${{ secrets.APPSETTINGS_JSON }}' > ${{ env.API_PROJECT_PATH }}/appsettings.json

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    name: Deploy to Somee via FTP
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

      - name: Upload to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ${{ env.PUBLISH_DIR }}/
          server-dir: /www.mfashionstore.somee.com
